# Generated by Django 3.0.4 on 2020-04-01 14:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.CharField(default=1, max_length=100, verbose_name=django.contrib.auth.models.AbstractUser),
            preserve_default=False,
        ),
    ]
