# Generated by Django 3.0.4 on 2020-04-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0002_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
